"""
Turning a decision transcript into something a person can read.

Three levels, and the separation is the design:

    1. THE PLAIN ANSWER -- one sentence, no jargon, no identifiers a human would have to
       decode. What happened to this credit and why.
    2. THE EVIDENCE -- typed references to the actual rows, so every claim in that
       sentence can be opened and checked against the source data rather than believed.
    3. THE TRANSCRIPT -- every tier tried, every candidate tested, the arithmetic in
       paise, and which layer objected.

**Why all three rather than the best one.** A finance operator clearing an exception
needs (1) and will resent (3). An auditor asked to sign off needs (3) and will not accept
(1) on its own. A judge asking "why did it match THAT payment" needs (2) to check that
the answer is not a story. Publishing only the readable layer is how reconciliation
tools end up unfalsifiable; publishing only the transcript is how they end up unused.

**Nothing here is generated by a model.** Every sentence is derived from the recorded
computation by the code below. `recon.llm` can rewrite an exception's prose afterwards,
but it never sources a fact -- see `llm/interface.py`. So an explanation cannot drift
from the decision it describes: there is no second inference that could disagree.
"""

from __future__ import annotations

from dataclasses import dataclass

import config as cfg

from .trace import CreditRecord

_TIER_NAME = {
    "tier1_reference": "reference match",
    "tier2_amount_date": "amount and date",
    "tier3_subsetsum": "combination search",
}


def plural(n: int, one: str, many: str = "") -> str:
    """`1 payment` / `4 payments`. Trivial, and its absence was visible in output."""
    return f"{n} {one}" if n == 1 else f"{n} {many or one + 's'}"


def rupees(paise: int | None) -> str:
    if paise is None:
        return "-"
    return f"Rs {paise / 100:,.2f}"


@dataclass(frozen=True, slots=True)
class EvidenceRef:
    """
    A pointer to a row a human can go and look at.

    `href` is a stable in-app anchor rather than a URL: the API is read-only and served
    from a static payload, so a link has to be resolvable by the client without asking
    the server for permission to look at data it already holds.
    """

    kind: str          # "payment" | "invoice" | "bank_txn"
    id: str
    label: str

    @property
    def href(self) -> str:
        return f"#/{self.kind}/{self.id}"

    def as_dict(self) -> dict:
        return {"kind": self.kind, "id": self.id, "label": self.label, "href": self.href}


@dataclass(frozen=True, slots=True)
class Step:
    """One line of the transcript."""

    seq: int
    stage: str
    headline: str
    detail: str
    evidence: tuple[EvidenceRef, ...] = ()

    def as_dict(self) -> dict:
        return {
            "seq": self.seq,
            "stage": self.stage,
            "headline": self.headline,
            "detail": self.detail,
            "evidence": [e.as_dict() for e in self.evidence],
        }


@dataclass(frozen=True, slots=True)
class Explanation:
    bank_txn_id: str
    verdict: str
    plain: str
    evidence: tuple[EvidenceRef, ...]
    steps: tuple[Step, ...]

    def as_dict(self) -> dict:
        return {
            "bank_txn_id": self.bank_txn_id,
            "verdict": self.verdict,
            "plain": self.plain,
            "evidence": [e.as_dict() for e in self.evidence],
            "transcript": [s.as_dict() for s in self.steps],
        }


class Explainer:
    """Renders `CreditRecord`s against the batch they came from."""

    def __init__(self, inputs) -> None:
        self._pay = {p.id: p for p in inputs.payments}
        self._inv = {i.invoice_no: i for i in inputs.invoices}
        self._txn = {t.id: t for t in inputs.bank_txns}

    # ---- evidence ------------------------------------------------------
    def payment_ref(self, pid: str) -> EvidenceRef:
        p = self._pay.get(pid)
        if p is None:
            return EvidenceRef("payment", pid, pid)
        inv = p.notes.get("invoice_no")
        who = self._inv[inv].customer_name if inv in self._inv else (p.contact or "")
        bits = [rupees(p.amount)]
        if who:
            bits.append(f"from {who}")
        if inv:
            bits.append(f"for {inv}")
        return EvidenceRef("payment", pid, " ".join(bits))

    def invoice_ref(self, no: str) -> EvidenceRef:
        i = self._inv.get(no)
        if i is None:
            return EvidenceRef("invoice", no, no)
        return EvidenceRef(
            "invoice", no, f"{no} - {i.customer_name}, {rupees(i.gross_amount)}"
        )

    def txn_ref(self, txn_id: str) -> EvidenceRef:
        t = self._txn.get(txn_id)
        if t is None:
            return EvidenceRef("bank_txn", txn_id, txn_id)
        return EvidenceRef(
            "bank_txn", txn_id, f"{t.txn_date} credit of {rupees(t.credit)}"
        )

    def _refs_for(self, rec: CreditRecord) -> tuple[EvidenceRef, ...]:
        refs = [self.txn_ref(rec.bank_txn_id)]
        for pid in rec.final_payment_ids:
            refs.append(self.payment_ref(pid))
            p = self._pay.get(pid)
            inv = p.notes.get("invoice_no") if p else None
            if inv:
                refs.append(self.invoice_ref(inv))
        for rival in rec.rivals:
            refs.append(self.txn_ref(rival))
        return tuple(refs)

    # ---- the plain sentence --------------------------------------------
    def _plain(self, rec: CreditRecord) -> str:
        amount = rupees(rec.credit_paise)
        won = next((a for a in rec.attempts if a.outcome == "assign"), None)

        if rec.verdict == "assign" and won is not None:
            n = len(rec.final_payment_ids)
            who = self._payer_of(rec.final_payment_ids)
            resid = won.residual_paise or 0
            fit = "exactly" if resid == 0 else f"to within {rupees(abs(resid))}"
            src = f" from {who}" if who else ""

            if n > 1:
                return (
                    f"This {amount} credit settles {plural(n, 'payment')} together"
                    f"{src}. Their expected amounts, after gateway fees and any TDS, "
                    f"add up to it {fit} - and no other combination of the "
                    f"{plural(rec.pool_size, 'payment')} in this settlement window does."
                )
            if won.tier == "tier1_reference":
                quoted = rec.parsed_ref or rec.ref_no or "a reference"
                return (
                    f"This {amount} credit is a single payment{src}. The bank line "
                    f"quotes {quoted}, which identifies that payment outright, and the "
                    f"amount agrees {fit}."
                )
            if won.tier == "tier2_amount_date":
                return (
                    f"This {amount} credit is a single payment{src} - the only one of "
                    f"the {plural(rec.pool_size, 'payment')} in the "
                    f"{cfg.LOOKBACK_DAYS}-day settlement window whose expected amount "
                    f"matches it, {fit}."
                )
            return (
                f"This {amount} credit is a single payment{src}, found by searching "
                f"combinations; the amounts agree {fit}."
            )

        if rec.verdict == "refuse":
            return self._plain_refusal(rec, amount)

        return (
            f"Nothing in the {cfg.LOOKBACK_DAYS}-day settlement window could account for "
            f"this {amount} credit, so no match was even proposed."
        )

    def _plain_refusal(self, rec: CreditRecord, amount: str) -> str:
        cat = rec.final_category
        if cat == "amount_name_conflict":
            bank_name = rec.parsed_payer or "the name on the bank line"
            expected = self._payer_of(rec.final_payment_ids) or "the customer on file"
            return (
                f"Not posted. The amounts agree exactly, but the payer on the bank line "
                f"({bank_name}) is not {expected}. Two independent checks disagree, so "
                f"this {amount} credit was left for a human rather than guessed."
            )
        if cat == "no_subset_fits":
            miss = self._closest_miss(rec)
            return (
                f"Not posted. Every combination of the "
                f"{plural(rec.pool_size, 'payment')} in this settlement window was "
                f"tested, and none adds up to this {amount} credit"
                + (f"; the closest came {miss} away" if miss else "")
                + ". The money is not accounted for by anything the engine can see."
            )
        if cat == "pool_exceeded":
            return (
                f"Not posted. {plural(rec.pool_size, 'payment')} settled in this window - above "
                f"the "
                f"{cfg.MAX_POOL} the engine can test exhaustively - so it declined to "
                f"search rather than check only part of the range and call the answer "
                f"unique."
            )
        if cat == "multiple_candidates":
            return (
                f"Not posted. More than one set of payments accounts for this {amount} "
                f"credit equally well, so the amount is not evidence for any particular "
                f"one. Both are listed below."
            )
        if cat == "solution_cap_reached":
            return (
                f"Not posted. So many different combinations fit this {amount} credit "
                f"that the amount identifies nothing."
            )
        if cat == "contested_payment":
            others = ", ".join(rec.rivals)
            return (
                f"Not posted. Another credit ({others}) has an equally good claim on the "
                f"same payments, and the evidence does not separate them - so neither "
                f"was posted."
            )
        if cat == "unexplained_residual":
            return (
                f"Not posted. The reference on this {amount} credit identifies a "
                f"payment, but the amount does not match what that payment should have "
                f"settled for. The amount is the stronger signal, so the reference was "
                f"not trusted on its own."
            )
        if cat == "narration_count_conflict":
            return (
                f"Not posted. The bank's own narration says this credit covers "
                f"{rec.parsed_txn_count} transaction(s), but the amounts fit a different "
                f"number. Two independent channels disagree."
            )
        if cat in ("fs_below_lower_threshold", "fs_review_band"):
            return (
                f"Not posted. The name and reference evidence for this {amount} credit "
                f"is too weak to support the match on its own and needs a human look."
            )
        if cat == "order_dependent_assignment":
            return (
                f"Not posted. This match appeared only in some orderings of the same "
                f"input, which means it was decided by the order rows happened to arrive "
                f"rather than by the data."
            )
        return f"Not posted ({cat or 'refused'}). {rec.final_reason}"

    def _payer_of(self, payment_ids) -> str:
        names = []
        for pid in payment_ids:
            p = self._pay.get(pid)
            inv = p.notes.get("invoice_no") if p else None
            if inv and inv in self._inv:
                names.append(self._inv[inv].customer_name)
        uniq = sorted(set(names))
        if not uniq:
            return ""
        return uniq[0] if len(uniq) == 1 else f"{len(uniq)} customers"

    @staticmethod
    def _closest_miss(rec: CreditRecord) -> str:
        for a in rec.attempts:
            if "closest miss" in a.reason:
                tail = a.reason.split("closest miss")[1].strip(" )")
                digits = "".join(c for c in tail if c.isdigit())
                if digits:
                    return rupees(int(digits))
        return ""

    # ---- the transcript -------------------------------------------------
    def _steps(self, rec: CreditRecord) -> tuple[Step, ...]:
        steps: list[Step] = []

        def add(stage, headline, detail, evidence=()):
            steps.append(Step(len(steps) + 1, stage, headline, detail, tuple(evidence)))

        add(
            "input",
            f"Read a {rupees(rec.credit_paise)} credit dated {rec.txn_date}.",
            f"Bank narration: {rec.narration!r}. Reference on the statement: "
            f"{rec.ref_no or '(none)'}.",
            [self.txn_ref(rec.bank_txn_id)],
        )
        read = []
        if rec.parsed_payer:
            read.append(f"payer {rec.parsed_payer!r}")
        if rec.parsed_ref:
            read.append(f"reference {rec.parsed_ref!r}")
        if rec.parsed_txn_count is not None:
            read.append(f"a stated count of {rec.parsed_txn_count} transaction(s)")
        add(
            "parse",
            "Read the narration." if read else "Nothing usable in the narration.",
            ("Extracted " + ", ".join(read) + ".") if read else
            "No payer name, reference or transaction count could be read from the text.",
        )
        add(
            "pool",
            f"Narrowed to {rec.pool_size} candidate payment(s).",
            f"Only payments settling between {rec.window_lo} and {rec.window_hi} "
            f"({cfg.LOOKBACK_DAYS}-day lookback) can belong to a credit on "
            f"{rec.txn_date}. {rec.claimed_at_decision} payment(s) were already claimed "
            f"by earlier credits and were excluded.",
        )

        for a in rec.attempts:
            label = _TIER_NAME.get(a.tier, a.tier)
            if a.outcome == "fell_through":
                add(
                    f"tier:{a.tier}",
                    f"Tried {label} - nothing conclusive.",
                    "This tier found no candidate it could stand behind, so the next "
                    "and weaker one was tried.",
                )
            elif a.outcome == "assign":
                add(
                    f"tier:{a.tier}",
                    f"{label.capitalize()} produced a match.",
                    self._arithmetic(a, rec.credit_paise),
                    [self.payment_ref(p) for p in a.payment_ids],
                )
            elif a.outcome == "conflict":
                add(
                    f"tier:{a.tier}",
                    f"{label.capitalize()} found a match the narration contradicts.",
                    "The bank's stated transaction count disagrees with the size of "
                    "this match, so it was not accepted.",
                )
            else:
                add(
                    f"tier:{a.tier}",
                    f"{label.capitalize()} refused: {a.category}.",
                    a.reason,
                    [self.payment_ref(p) for p in a.payment_ids],
                )

        if rec.fs_fields or rec.fs_weight is not None:
            verdict = (
                "The non-amount evidence CONTRADICTS the amount evidence."
                if rec.fs_contradicts
                else "The non-amount evidence does not contradict the amount evidence."
            )
            lines = [
                f"  {f.field}: {f.level.lower()} ({f.weight:+.2f} bits)"
                + (f" - {f.detail}" if f.detail else "")
                for f in rec.fs_fields
            ]
            # Built as a list rather than a chain of `+` with a ternary in the middle.
            # Written that way first, the ternary bound across the whole expression and
            # silently swallowed the total -- the one number a reader most wants.
            total = "no comparable field" if rec.fs_weight is None else f"{rec.fs_weight:+.2f} bits"
            body = [
                "Fellegi-Sunter match weight, in bits. Positive supports the match, "
                "negative opposes it; the two thresholds are "
                f"{cfg.FS_THRESHOLD_LOWER} and {cfg.FS_THRESHOLD_UPPER}.",
                *lines,
            ]
            if rec.fs_prior is not None:
                body.append(
                    f"  prior from the blocking pool: {rec.fs_prior:+.2f} "
                    f"(1 in {rec.pool_size} payments in the window would match by chance)"
                )
            body.append(f"  TOTAL: {total}")
            add(
                "layer3",
                f"Weighed the name and reference evidence. {verdict}",
                "\n".join(body),
            )

        if rec.rivals:
            add(
                "resolve",
                f"Contested by {len(rec.rivals)} other credit(s).",
                "Both credits bid for the same payments with evidence the engine could "
                "not separate. A tie is not broken - it means the data does not identify "
                "an owner - so neither was posted.",
                [self.txn_ref(t) for t in rec.rivals],
            )
        elif rec.granted:
            add(
                "resolve",
                "No other credit wanted these payments.",
                "The bid was uncontested and was granted in round "
                f"{rec.round_no} of the fixpoint loop.",
            )

        add(
            "verdict",
            {"assign": "POSTED.", "refuse": "REFUSED - sent to a human.",
             "none": "NO CANDIDATE."}.get(rec.verdict, rec.verdict.upper()),
            rec.final_reason or self._plain(rec),
            self._refs_for(rec),
        )
        return tuple(steps)

    @staticmethod
    def _arithmetic(a, credit_paise: int) -> str:
        if a.interval_lo is None:
            return a.reason or "Matched."
        span = (
            f"exactly {rupees(a.interval_lo)}"
            if a.interval_lo == a.interval_hi
            else f"between {rupees(a.interval_lo)} and {rupees(a.interval_hi)}"
        )
        fee = (
            "the gateway fee is known exactly from the payment record"
            if a.certain_fee
            else f"the fee is not on the record, so it was bounded by the "
                 f"{cfg.MDR_RATE_BAND[0]:.1%}-{cfg.MDR_RATE_BAND[1]:.1%} rate band"
        )
        margin = (
            ""
            if a.uniqueness_margin is None
            else f" Uniqueness margin {a.uniqueness_margin:.2f}: how far the "
                 f"next-best combination sat outside tolerance."
        )
        return (
            f"After gateway fees and any TDS, the payment(s) should have settled for "
            f"{span}. The bank credited {rupees(credit_paise)}, leaving a residual of "
            f"{a.residual_paise:+d} paise - inside the {cfg.TOL_ABS_PAISE}-paise "
            f"tolerance fixed before the run. Here {fee}.{margin}"
        )

    # ---- entry point ----------------------------------------------------
    def explain(self, rec: CreditRecord) -> Explanation:
        return Explanation(
            bank_txn_id=rec.bank_txn_id,
            verdict=rec.verdict,
            plain=self._plain(rec),
            evidence=self._refs_for(rec),
            steps=self._steps(rec),
        )

    def explain_all(self, recorder) -> dict[str, Explanation]:
        return {k: self.explain(v) for k, v in recorder.records.items()}
